(() => {
  const STORE = 'anveraPortalPrototype';
  const load = () => {
    const d = JSON.parse(localStorage.getItem(STORE) || '{}');
    return {inquiries:[],projects:[],payments:[],tickets:[],files:[],proposals:[],changeRequests:[],events:[],...d};
  };
  const save = d => localStorage.setItem(STORE, JSON.stringify(d));
  const esc = (v='') => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const uid = () => crypto.randomUUID();
  const money = v => Number(v||0).toLocaleString('en-US',{style:'currency',currency:'USD'});

  const style=document.createElement('style');
  style.textContent=`
    .record-actions{position:relative;margin-left:auto}.more-btn{width:34px;height:34px;border:1px solid rgba(30,46,30,.12);background:#fff;border-radius:9px;cursor:pointer;font-size:18px;line-height:1}.more-menu{position:absolute;right:0;top:40px;width:205px;background:#fff;border:1px solid rgba(30,46,30,.12);border-radius:12px;padding:6px;box-shadow:0 18px 55px rgba(20,30,20,.16);z-index:50;display:none}.record-actions.open .more-menu{display:block}.more-menu button{width:100%;border:0;background:none;text-align:left;padding:10px 11px;border-radius:8px;font-size:12px;cursor:pointer;color:#29291f}.more-menu button:hover{background:#f2efe7}.more-menu .danger{color:#9a4039}.more-menu hr{border:0;border-top:1px solid rgba(30,46,30,.09);margin:5px}
    .manage-overlay{position:fixed;inset:0;background:rgba(15,24,15,.58);backdrop-filter:blur(5px);z-index:1300;display:none;align-items:center;justify-content:center;padding:22px}.manage-overlay.open{display:flex}.manage-card{width:min(760px,100%);max-height:92vh;overflow:auto;background:#f7f4ee;border-radius:22px;padding:28px;box-shadow:0 30px 90px rgba(0,0,0,.3)}.manage-head{display:flex;justify-content:space-between;gap:20px;margin-bottom:22px}.manage-head h3{font:600 38px 'Cormorant Garamond';margin:5px 0}.manage-head p{font-size:14px;color:#756f63;line-height:1.55}.manage-close{width:40px;height:40px;border:1px solid rgba(30,46,30,.14);background:#fff;border-radius:10px;font-size:22px;cursor:pointer}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.detail-item{background:#fff;border:1px solid rgba(30,46,30,.1);border-radius:12px;padding:14px}.detail-item.full{grid-column:1/-1}.detail-item small{display:block;color:#756f63;font-size:10px;text-transform:uppercase;letter-spacing:.08em;margin-bottom:5px}.detail-item strong,.detail-item span{font-size:14px;line-height:1.55}.manage-form{display:grid;grid-template-columns:1fr 1fr;gap:15px}.manage-field.full{grid-column:1/-1}.manage-field label{display:block;font-size:13px;font-weight:700;margin-bottom:7px}.manage-field input,.manage-field select,.manage-field textarea{width:100%;padding:13px 14px;border:1px solid rgba(30,46,30,.14);background:#fff;border-radius:10px;font-size:14px}.manage-field textarea{min-height:95px;resize:vertical}.manage-footer{display:flex;justify-content:flex-end;gap:10px;margin-top:22px;padding-top:17px;border-top:1px solid rgba(30,46,30,.1)}
    .inline-tools{display:flex;gap:8px;align-items:center}.secondary-action{border:1px solid rgba(30,46,30,.13);background:#fff;color:#1e2e1e;border-radius:10px;padding:11px 14px;font-size:12px;font-weight:700;cursor:pointer}.summary-strip{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:17px}.summary-strip .card{padding:16px}.workflow-card{background:rgba(255,255,255,.72);border:1px solid rgba(30,46,30,.12);border-radius:16px;padding:20px}.workflow-card h4{font:600 25px 'Cormorant Garamond';margin:8px 0}.workflow-card p{font-size:12px;color:#756f63;line-height:1.6}.workflow-meta{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.compact-list{display:grid;gap:10px}.compact-row{display:flex;gap:12px;align-items:center;background:rgba(255,255,255,.72);border:1px solid rgba(30,46,30,.1);border-radius:13px;padding:14px}.compact-row>div:first-of-type{flex:1}.compact-row strong,.compact-row small{display:block}.compact-row strong{font-size:14px}.compact-row small{font-size:11px;color:#756f63;margin-top:3px}
    @media(max-width:700px){.detail-grid,.manage-form,.summary-strip{grid-template-columns:1fr}.detail-item.full,.manage-field.full{grid-column:auto}.manage-card{padding:21px}.manage-head h3{font-size:32px}.more-menu{position:fixed;left:16px;right:16px;bottom:16px;top:auto;width:auto}}
  `;
  document.head.appendChild(style);
  document.body.insertAdjacentHTML('beforeend','<div id="manageOverlay" class="manage-overlay"><div class="manage-card"><div class="manage-head"><div><span id="manageEye" class="eye"></span><h3 id="manageTitle"></h3><p id="manageDesc"></p></div><button id="manageClose" class="manage-close">×</button></div><div id="manageBody"></div></div></div>');
  const overlay=document.querySelector('#manageOverlay'), body=document.querySelector('#manageBody');
  const close=()=>overlay.classList.remove('open');
  document.querySelector('#manageClose').onclick=close;
  overlay.addEventListener('click',e=>{if(e.target===overlay)close()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
  const open=(eye,title,desc,html)=>{document.querySelector('#manageEye').textContent=eye;document.querySelector('#manageTitle').textContent=title;document.querySelector('#manageDesc').textContent=desc;body.innerHTML=html;overlay.classList.add('open')};
  const detail=(label,value,full=false)=>`<div class="detail-item ${full?'full':''}"><small>${label}</small><span>${esc(value||'—')}</span></div>`;
  const f=(name,label,value='',type='text',full=false,options=[])=>`<div class="manage-field ${full?'full':''}"><label>${label}</label>${type==='textarea'?`<textarea name="${name}">${esc(value)}</textarea>`:type==='select'?`<select name="${name}">${options.map(o=>`<option ${o===value?'selected':''}>${esc(o)}</option>`).join('')}</select>`:`<input name="${name}" type="${type}" value="${esc(value)}">`}</div>`;
  const footer=label=>`<div class="manage-footer"><button type="button" class="secondary-action" data-manage-close>Cancel</button><button class="action">${label}</button></div>`;
  const reload=()=>location.reload();

  function menu(type,id,items){return `<div class="record-actions"><button class="more-btn" aria-label="Record actions">•••</button><div class="more-menu">${items.map(i=>i==='-'?'<hr>':`<button class="${i.danger?'danger':''}" data-manage-action="${i.action}" data-type="${type}" data-id="${id}">${i.label}</button>`).join('')}</div></div>`}
  function attachMenus(){
    let d=load();
    document.querySelectorAll('#inquiries tbody tr').forEach((row,i)=>{if(row.querySelector('.record-actions')||!d.inquiries[i])return;row.lastElementChild.innerHTML=menu('inquiry',d.inquiries[i].id,[{label:'View details',action:'view'},{label:'Edit inquiry',action:'edit'},{label:'Schedule meeting',action:'meeting'},{label:'Create proposal',action:'proposal'},{label:'Convert to project',action:'convert'},'-',{label:'Archive / delete',action:'delete',danger:true}]);});
    document.querySelectorAll('#projects .project').forEach((card,i)=>{if(card.querySelector('.record-actions')||!d.projects[i])return;card.insertAdjacentHTML('afterbegin',menu('project',d.projects[i].id,[{label:'View project',action:'view'},{label:'Edit project',action:'edit'},{label:'Update stage & progress',action:'progress'},{label:'Add task',action:'task'},{label:'Add change request',action:'change'},'-',{label:'Archive / delete',action:'delete',danger:true}]));});
    document.querySelectorAll('#finances tbody tr').forEach((row,i)=>{if(row.querySelector('.record-actions')||!d.payments[i])return;const td=document.createElement('td');td.innerHTML=menu('payment',d.payments[i].id,[{label:'View payment',action:'view'},{label:'Edit payment',action:'edit'},{label:'Mark as paid',action:'paid'},'-',{label:'Delete record',action:'delete',danger:true}]);row.appendChild(td);});
    const financeHead=document.querySelector('#finances thead tr');if(financeHead&&!financeHead.querySelector('[data-actions-head]'))financeHead.insertAdjacentHTML('beforeend','<th data-actions-head>Actions</th>');
    document.querySelectorAll('#support tbody tr').forEach((row,i)=>{if(row.querySelector('.record-actions')||!d.tickets[i])return;const td=document.createElement('td');td.innerHTML=menu('ticket',d.tickets[i].id,[{label:'View ticket',action:'view'},{label:'Edit ticket',action:'edit'},{label:'Change status',action:'status'},{label:'Convert to change request',action:'change'},'-',{label:'Delete ticket',action:'delete',danger:true}]);row.appendChild(td);});
    const supportHead=document.querySelector('#support thead tr');if(supportHead&&!supportHead.querySelector('[data-actions-head]'))supportHead.insertAdjacentHTML('beforeend','<th data-actions-head>Actions</th>');
    document.querySelectorAll('#files .file').forEach((card,i)=>{if(card.querySelector('.record-actions')||!d.files[i])return;card.lastElementChild.outerHTML=menu('file',d.files[i].id,[{label:'View information',action:'view'},{label:'Edit information',action:'edit'},'-',{label:'Delete file record',action:'delete',danger:true}]);});
  }

  const find=(d,type,id)=>{const key={inquiry:'inquiries',project:'projects',payment:'payments',ticket:'tickets',file:'files'}[type];return {key,item:d[key]?.find(x=>x.id===id)}};
  function viewRecord(type,item){
    const maps={
      inquiry:[['Contact',item.name],['Business',item.business],['Phone',item.phone],['Email',item.email],['Project type',item.projectType],['Source',item.source],['Status',item.status],['Follow-up',item.followUp],['Customer need',item.description,true]],
      project:[['Project',item.projectName],['Client',item.client],['Type',item.projectType],['Status',item.status],['Progress',(item.progress||0)+'%'],['Start date',item.startDate],['Project value',money(item.value)],['Deposit',money(item.deposit)],['Scope',item.notes,true]],
      payment:[['Client',item.client],['Type',item.type],['Amount',money(item.amount)],['Status',item.status],['Due date',item.dueDate],['Paid date',item.paidDate],['Invoice',item.invoice],['Method',item.method]],
      ticket:[['Client',item.client],['Category',item.category],['Priority',item.priority],['Status',item.status],['Description',item.description,true]],
      file:[['Client / project',item.client],['Title',item.title],['Category',item.category],['File name',item.fileName],['Notes',item.notes,true]]
    };
    open('Record details',maps[type][0][1]||'Information','Review the saved information and use the record menu to make changes.',`<div class="detail-grid">${maps[type].map(x=>detail(x[0],x[1],x[2])).join('')}</div><div class="manage-footer"><button class="action" data-manage-close>Done</button></div>`);
  }
  function editRecord(type,item){
    let fields='';
    if(type==='inquiry')fields=f('name','Contact name',item.name)+f('business','Business name',item.business)+f('phone','Phone',item.phone)+f('email','Email',item.email,'email')+f('projectType','Project type',item.projectType,'select',false,['TYPE 1 — Website only','TYPE 2 — Website + backend monitoring','TYPE 3 — Website + backend + forecasting / advanced calculations'])+f('status','Status',item.status,'select',false,['New','Reviewing','Meeting scheduled','Proposal sent','Accepted','Declined','Archived'])+f('description','Customer need',item.description,'textarea',true);
    if(type==='project')fields=f('projectName','Project name',item.projectName)+f('client','Client',item.client)+f('status','Status',item.status,'select',false,['Not started','Research','Planning','Creating','Implementing','Waiting on customer','Paused','Delayed','Completed'])+f('progress','Progress %',item.progress||0,'number')+f('value','Project value',item.value,'number')+f('startDate','Start date',item.startDate,'date')+f('notes','Scope summary',item.notes,'textarea',true);
    if(type==='payment')fields=f('client','Client',item.client)+f('amount','Amount',item.amount,'number')+f('type','Type',item.type,'select',false,['Project deposit','Project milestone','Final payment','Monthly subscription','Additional work'])+f('status','Status',item.status,'select',false,['Paid','Upcoming','Due','Partially paid','Overdue'])+f('dueDate','Due date',item.dueDate,'date')+f('invoice','Invoice',item.invoice);
    if(type==='ticket')fields=f('client','Client',item.client)+f('category','Category',item.category)+f('priority','Priority',item.priority,'select',false,['Low','Normal','High'])+f('status','Status',item.status,'select',false,['New','Reviewing','In progress','Waiting on customer','Resolved','Closed'])+f('description','Description',item.description,'textarea',true);
    if(type==='file')fields=f('client','Client / project',item.client)+f('title','Title',item.title)+f('category','Category',item.category)+f('fileName','File name',item.fileName)+f('notes','Notes',item.notes,'textarea',true);
    open('Edit record','Update information','Only the fields that matter for this record are shown.',`<form id="manageEditForm" data-edit-type="${type}" data-edit-id="${item.id}" class="manage-form">${fields}${footer('Save changes')}</form>`);
  }
  function simpleForm(eye,title,desc,mode,type,id,fields,label='Save'){
    open(eye,title,desc,`<form id="manageSpecialForm" data-mode="${mode}" data-type="${type}" data-id="${id}" class="manage-form">${fields}${footer(label)}</form>`);
  }

  document.addEventListener('click',e=>{
    const more=e.target.closest('.more-btn');if(more){e.stopPropagation();document.querySelectorAll('.record-actions.open').forEach(x=>{if(x!==more.parentElement)x.classList.remove('open')});more.parentElement.classList.toggle('open');return;}
    if(!e.target.closest('.record-actions'))document.querySelectorAll('.record-actions.open').forEach(x=>x.classList.remove('open'));
    if(e.target.matches('[data-manage-close]'))close();
    const a=e.target.closest('[data-manage-action]');if(!a)return;
    const d=load(),{key,item}=find(d,a.dataset.type,a.dataset.id);if(!item)return;
    const type=a.dataset.type,act=a.dataset.manageAction;
    if(act==='view')viewRecord(type,item);
    if(act==='edit')editRecord(type,item);
    if(act==='delete'){if(confirm('Remove this record from the prototype?')){d[key]=d[key].filter(x=>x.id!==item.id);save(d);reload();}}
    if(act==='paid'){item.status='Paid';item.paidDate=new Date().toISOString().slice(0,10);save(d);reload();}
    if(act==='meeting')simpleForm('Inquiry follow-up','Schedule meeting','Set the meeting details. Calendar and email sending will be connected later.','meeting',type,item.id,f('date','Meeting date','','date')+f('time','Meeting time','','time')+f('method','Method','Google Meet','select',false,['Google Meet','Zoom','Phone call','In person'])+f('location','Link or location')+f('notes','Preparation notes','','textarea',true),'Schedule meeting');
    if(act==='proposal')simpleForm('Proposal','Create proposal summary','Record the proposed scope, pricing, payment schedule, and customer response.','proposal',type,item.id,f('title','Proposal title',`${item.business||item.name} project proposal`)+f('amount','Project price','','number')+f('monthly','Monthly service','','number')+f('status','Status','Draft','select',false,['Draft','Sent','Changes requested','Accepted','Declined'])+f('scope','Scope summary',item.description||'','textarea',true),'Save proposal');
    if(act==='convert')simpleForm('Project conversion','Convert inquiry to project','Create a project from this inquiry without re-entering the customer information.','convert',type,item.id,f('projectName','Project name',`${item.business||item.name} system`)+f('startDate','Planned start','','date')+f('value','Project value','','number')+f('researchDays','Research days','5','number')+f('planningDays','Planning days','7','number')+f('creatingDays','Creating days','20','number')+f('implementingDays','Implementing days','7','number'),'Create project');
    if(act==='progress')simpleForm('Project update','Update stage and progress','Keep the customer-facing status clear without exposing internal details.','progress',type,item.id,f('status','Current stage',item.status,'select',false,['Not started','Research','Planning','Creating','Implementing','Waiting on customer','Paused','Delayed','Completed'])+f('progress','Overall progress %',item.progress||0,'number')+f('customerUpdate','Customer-visible update',item.customerUpdate||'','textarea',true)+f('internalNote','Internal note',item.internalNote||'','textarea',true),'Update project');
    if(act==='task')simpleForm('Project task','Add a task','Tasks stay inside the project and do not clutter the main dashboard.','task',type,item.id,f('title','Task title')+f('stage','Stage','Research','select',false,['Research','Planning','Creating','Implementing'])+f('dueDate','Due date','','date')+f('priority','Priority','Normal','select',false,['Low','Normal','High','Urgent'])+f('visible','Visibility','Internal only','select',false,['Internal only','Customer visible'])+f('notes','Task notes','','textarea',true),'Add task');
    if(act==='change')simpleForm('Change request','Add change request','Track work outside the original scope and whether it should be billed.','change',type,item.id,f('title','Request title')+f('status','Status','Reviewing','select',false,['Requested','Reviewing','Quoted','Approved','Declined','In progress','Completed'])+f('billable','Billing','Billable','select',false,['Included','Billable'])+f('amount','Additional cost','','number')+f('days','Added timeline days','','number')+f('description','Description','','textarea',true),'Save change request');
    if(act==='status')simpleForm('Support workflow','Update ticket status','Move the request through the support process.','ticketStatus',type,item.id,f('status','Status',item.status,'select',false,['New','Reviewing','In progress','Waiting on customer','Resolved','Closed'])+f('note','Status note','','textarea',true),'Update status');
  });

  document.addEventListener('submit',e=>{
    if(e.target.id==='manageEditForm'){
      e.preventDefault();const d=load(),{item}=find(d,e.target.dataset.editType,e.target.dataset.editId);if(!item)return;Object.assign(item,Object.fromEntries(new FormData(e.target)));save(d);reload();
    }
    if(e.target.id==='manageSpecialForm'){
      e.preventDefault();const d=load(),values=Object.fromEntries(new FormData(e.target)),mode=e.target.dataset.mode,id=e.target.dataset.id,{item}=find(d,e.target.dataset.type,id);if(!item)return;
      if(mode==='meeting'){item.meeting=values;item.status='Meeting scheduled';d.events.push({...values,id:uid(),type:'Meeting',title:`Meeting — ${item.business||item.name}`,relatedId:id});}
      if(mode==='proposal'){d.proposals.push({...values,id:uid(),inquiryId:id,client:item.business||item.name,createdAt:new Date().toISOString()});item.status=values.status==='Accepted'?'Accepted':'Proposal sent';}
      if(mode==='convert'){d.projects.unshift({...values,id:uid(),client:item.business||item.name,projectType:item.projectType,status:'Not started',progress:0,notes:item.description,createdAt:new Date().toISOString()});item.status='Accepted';}
      if(mode==='progress')Object.assign(item,values);
      if(mode==='task'){item.tasks=item.tasks||[];item.tasks.push({...values,id:uid(),status:'Open'});}
      if(mode==='change'){d.changeRequests.push({...values,id:uid(),relatedId:id,relatedType:e.target.dataset.type,createdAt:new Date().toISOString()});}
      if(mode==='ticketStatus'){item.status=values.status;item.statusNote=values.note;}
      save(d);reload();
    }
  });

  function addWorkflowViews(){
    const nav=document.querySelector('#adminNav');if(nav&&!nav.querySelector('[data-page="workflow"]'))nav.insertAdjacentHTML('beforeend','<button data-page="workflow">Workflow</button>');
    const content=document.querySelector('.content');if(content&&!document.querySelector('#workflow'))content.insertAdjacentHTML('beforeend','<section id="workflow" class="section"></section>');
    const d=load(),el=document.querySelector('#workflow');if(!el)return;
    el.innerHTML=`<div class="head"><div><span class="eye">Supporting workflow</span><h3>Proposals, changes & calendar</h3><p>Secondary work is kept in one place so the main navigation stays simple.</p></div><div class="inline-tools"><button class="secondary-action" data-workflow-add="event">+ Event</button></div></div><div class="summary-strip"><article class="card"><span>Proposals</span><strong>${d.proposals.length}</strong><small>Drafts and responses</small></article><article class="card"><span>Change requests</span><strong>${d.changeRequests.length}</strong><small>Scope additions</small></article><article class="card"><span>Calendar items</span><strong>${d.events.length}</strong><small>Meetings and deadlines</small></article></div><div class="grid equal"><article class="panel"><span class="eye">Proposals</span><h3>Customer decisions</h3>${d.proposals.length?`<div class="compact-list">${d.proposals.map(x=>`<div class="compact-row"><div><strong>${esc(x.title)}</strong><small>${esc(x.client)} · ${money(x.amount)} · ${esc(x.status)}</small></div></div>`).join('')}</div>`:'<div class="empty-state"><strong>No proposals</strong><span>Create one from an inquiry record.</span></div>'}</article><article class="panel"><span class="eye">Change requests</span><h3>Additional scope</h3>${d.changeRequests.length?`<div class="compact-list">${d.changeRequests.map(x=>`<div class="compact-row"><div><strong>${esc(x.title)}</strong><small>${esc(x.status)} · ${esc(x.billable)} · ${money(x.amount)}</small></div></div>`).join('')}</div>`:'<div class="empty-state"><strong>No change requests</strong><span>Create one from a project or support ticket.</span></div>'}</article></div><div class="panel" style="margin-top:17px"><span class="eye">Calendar</span><h3>Meetings and deadlines</h3>${d.events.length?`<div class="compact-list">${d.events.map(x=>`<div class="compact-row"><div><strong>${esc(x.title)}</strong><small>${esc(x.date)} ${esc(x.time||'')} · ${esc(x.type)}</small></div></div>`).join('')}</div>`:'<div class="empty-state"><strong>No calendar items</strong><span>Meetings and manually added events will appear here.</span></div>'}</div>`;
    nav?.querySelector('[data-page="workflow"]')?.addEventListener('click',()=>{document.querySelectorAll('.section').forEach(x=>x.classList.toggle('on',x.id==='workflow'));document.querySelectorAll('.nav button').forEach(x=>x.classList.toggle('on',x.dataset.page==='workflow'));document.querySelector('#topEye').textContent='Supporting workflow';document.querySelector('#topTitle').textContent='Proposals, changes & calendar';});
  }
  document.addEventListener('click',e=>{if(e.target.matches('[data-workflow-add="event"]'))simpleForm('Calendar','Add calendar item','Add only important meetings, deadlines, payment dates, or launch milestones.','event','event','',f('title','Event title')+f('date','Date','','date')+f('time','Time','','time')+f('type','Type','Meeting','select',false,['Meeting','Follow-up','Project deadline','Payment due','Launch','Maintenance'])+f('notes','Notes','','textarea',true),'Add event');});
  document.addEventListener('submit',e=>{if(e.target.id==='manageSpecialForm'&&e.target.dataset.mode==='event'){e.preventDefault();const d=load(),values=Object.fromEntries(new FormData(e.target));d.events.push({...values,id:uid()});save(d);reload();}} ,true);

  const observer=new MutationObserver(()=>attachMenus());observer.observe(document.body,{childList:true,subtree:true});
  setTimeout(()=>{attachMenus();addWorkflowViews();},250);
})();